
<?php $imp=$this->myUser->getImpot();?>
<script type="text/javascript">

$(document).ready(function() {
	$("#onTalk").val(0);
	$("#onMyTalk").val(0);
	aniX = 0;
	aniY = 0;
	
	jQuery.fn.arretGch = function() {
		$(this).oneTime(200,function() {
			$(this).css({backgroundPosition:'-23px -28px'});
		}).oneTime(400,function() {
			$(this).css({backgroundPosition:'-123px -28px'});
		}).oneTime(600,function() {
			$(this).css({backgroundPosition:'-223px -28px'});
		}).oneTime(800,function() {
			$(this).css({backgroundPosition:'-123px -28px'});
		});
	};
	
	jQuery.fn.mouvArretGch = function(){
		$(this).arretGch();
		$(this).everyTime(800,function(){
			$(this).arretGch();
		});
	}
	jQuery.fn.marcheGch = function() {
		$(this).oneTime(200,function() {
			$(this).css({backgroundPosition:'-23px -228px'});
		}).oneTime(400,function() {
			$(this).css({backgroundPosition:'-123px -228px'});
		}).oneTime(600,function() {
			$(this).css({backgroundPosition:'-223px -228px'});
		}).oneTime(800,function() {
			$(this).css({backgroundPosition:'-323px -228px'});
		});
	};
	jQuery.fn.mouvMarcheGch = function(){
		$(this).marcheGch();
		$(this).everyTime(800,function(){
			$(this).marcheGch();
		});
	}
	
	///
	
	jQuery.fn.arretTalk = function() {
		$(this).oneTime(200,function() {
			$(this).css({backgroundPosition:'-10px 1px'});
		}).oneTime(400,function() {
			$(this).css({backgroundPosition:'-10px -281px'});
		}).oneTime(600,function() {
			$(this).css({backgroundPosition:'-10px -541px'});
		}).oneTime(800,function() {
			$(this).css({backgroundPosition:'-10px -281px'});
		});
	};
	
	jQuery.fn.mouvArretTalk = function(){
		$(this).arretTalk();
		$(this).everyTime(800,function(){
			$(this).arretTalk();
		});
	}
	jQuery.fn.marcheTalk = function() {
		$(this).oneTime(200,function() {
			$(this).css({backgroundPosition:'-175px 1px'});
		}).oneTime(400,function() {
			$(this).css({backgroundPosition:'-346px 1px'});
		}).oneTime(600,function() {
			$(this).css({backgroundPosition:'-175px 1px'});
		}).oneTime(800,function() {
			$(this).css({backgroundPosition:'-11px 1px'});
		});
	};
	jQuery.fn.mouvMarcheTalk = function(){
		$(this).marcheTalk();
		$(this).everyTime(800,function(){
			$(this).marcheTalk();
		});
	}
	
	var arret = 0;

	$("#sayyaoto").click(function() {
		if($("#onTalk").val()==0 && $("#onMyTalk").val()==0){
			$("#texto").removeClass().addClass('sayyaotoTextCouloir');
			if (arret == 0 || arrestation==1) {
				$("#texto").show();
				$("#onTalk").val(1);
				$("#sayyaoto").stopTime().mouvMarcheGch();

				var request = $.ajax({
				url: url_site+"Core/index/ajaxquote", 
				type: "POST",
				data: { idDiv: 'sayyaoto', idPerso: '3', talk: 'mouvArretGch', stopTalk: 'mouvMarcheGch' },			
				
				}); 
				request.done(function(msg) { 
				$("#texto").html(msg); 
				});
				 
			}else{
				arret = 0;
				$("#sayyaoto").stopTime().mouvArretGch();
				$("#texto").invisible();
			}
		}
	});
	
	$("#garde_couloir_1").click(function() {
		if($("#onTalk").val()==0 && $("#onMyTalk").val()==0){
			$("#texto").removeClass().addClass('garde_couloir_1TextCouloir');
			if (arret == 0 || arrestation==1) {
				$("#texto").show();
				$("#onTalk").val(1);
				$("#garde_couloir_1").stopTime().mouvMarcheTalk();

				var request = $.ajax({
				url: url_site+"Core/index/ajaxquote", 
				type: "POST",
				data: { idDiv: 'garde_couloir_1', idPerso: '12', talk: 'mouvArretTalk', stopTalk: 'mouvMarcheTalk' },			
				
				}); 
				request.done(function(msg) { 
				$("#texto").html(msg); 
				});
				 
			}else{
				arret = 0;
				$("#garde_couloir_1").stopTime().mouvArretTalk();
				$("#texto").invisible();
			}
		}
	});

$("#retour_couloir2").click(function() {
	if($('#onTalk').val()==0){
		$('#onTalk').val(1);	
		if(<?php echo $imp;?>>=5)
			var dstination='trone';else dstination='commune';
		var request = $.ajax({
		url: url_site+'Core/index/'+dstination,
		type: "POST"							
		}); 
		request.done(function(msg) {
						$("#inThePlace").fadeOut(1000);
						setTimeout(function(){
						  $("#inThePlace").hide();
						  $("#inThePlace").html(msg); 
						$("#inThePlace").fadeIn(1000);
						}, 1000);
						
					});
	}
});
$(".vers_trone").click(function() {
	if($('#onTalk').val()==0){
		$('#onTalk').val(1);
		var request = $.ajax({
		url: url_site+'Core/index/trone',
		type: "POST",							
		}); 
		request.done(function(msg) {
						$("#inThePlace").fadeOut(1000);
						setTimeout(function(){
						  $("#inThePlace").hide();
						  $("#inThePlace").html(msg); 
						$("#inThePlace").fadeIn(1000);
						}, 1000);
						
					});
	}
});

$("#porte_3").click(function() {
		if($("#onTalk").val()==0 && $("#onMyTalk").val()==0){
			if($(this).attr('class')=='porte_9_1'){
				if(<?php echo $imp;?>>=5)
					var dstination='trone';else dstination='magasinpalais';
				var request = $.ajax({ 
					url: url_site+'Core/index/'+dstination,
					type: "POST"							
		}); 
		request.done(function(msg) {
						$("#inThePlace").fadeOut(1000);
						setTimeout(function(){
						  $("#inThePlace").hide();
						  $("#inThePlace").html(msg); 
						$("#inThePlace").fadeIn(1000);
						}, 1000);
						
					});
			}
		}
	});

});
 
if($("#sayyaoto").length)
	$("#sayyaoto").mouvArretGch();
if($("#garde_couloir_1").length)
	$("#garde_couloir_1").mouvArretTalk();

var heureActu=$('.progBarText').html();
if(heureActu=="12h30" || heureActu=="16h00" || heureActu=="18h00" )
	$("#porte_3").removeClass().addClass('porte_9_1');

$("#mesTexto").html('<img src="images/plan/couloir2_plan.png" />'); 
$("#plan").val('couloir_plan');

</script>
</head>

<?php
if($this->myUser->getHeure()>=67)$stylePiece='nuit';else $stylePiece='';
$stylePiece='';
?>
<div id="<?php echo $this->salle;?>" class='<?php echo $stylePiece;?>'>
	<div class='vers_trone'>&nbsp;</div>
	<div id="perso"></div><p>&nbsp;</p>
	<div id='retour_couloir2' style='z-index:1000'></div>
	<?php
	
	foreach($this->porteDansSalle as $porte){
		echo '<div id="porte_'.$porte['por_id'].'" class="porte_'.$porte['por_id_type'].'_'.$porte['poru_etat'].'"></div>';
	}	?>
	<div id="texto"></div>
	<?php foreach($this->persoDansSalle as $clef => $perso){
		echo '<div class="'.$clef.'_couloir2" id="'.$clef.'"></div>';
	}
	?>
</div>


