
<?php $imp=$this->myUser->getImpot();?>
<script type="text/javascript">

$(document).ready(function() {
	$("#onTalk").val(0);
	$("#onMyTalk").val(0);
	aniX = 0;
	aniY = 0;
	
	jQuery.fn.arretGch = function() {
		$(this).oneTime(200,function() {
			$(this).css({backgroundPosition:'0px 10px'});
		}).oneTime(400,function() {
			$(this).css({backgroundPosition:'0px -63px'});
		}).oneTime(600,function() {
			$(this).css({backgroundPosition:'0px -135px'});
		}).oneTime(800,function() {
			$(this).css({backgroundPosition:'0px -63px'});
		})
	};
	
	jQuery.fn.mouvArretGch = function(){
		// $(this).arretGch();
		// $(this).everyTime(800,function(){
			// $(this).arretGch();
		// });
	}
	jQuery.fn.marcheGch = function() {
		$(this).oneTime(1200,function() {
			$(this).css({backgroundPosition:'-249px 10px'});
		}).oneTime(300,function() {
			$(this).css({backgroundPosition:'-334px 10px'});
		}).oneTime(600,function() {
			$(this).css({backgroundPosition:'-417px 10px'});
		}).oneTime(900,function() {
			$(this).css({backgroundPosition:'-334px 10px'});
		});
	};
	jQuery.fn.mouvMarcheGch = function(){
		$(this).marcheGch();
		$(this).everyTime(1200,function(){
			$(this).marcheGch();
		});
	}
	
	///
	
	jQuery.fn.arretTalk = function() {
		$(this).oneTime(1200,function() {
			$(this).css({backgroundPosition:'0px 0px'});
		}).oneTime(300,function() {
			$(this).css({backgroundPosition:'-100px 0px'});
		}).oneTime(600,function() {
			$(this).css({backgroundPosition:'-200px 0px'});
		}).oneTime(900,function() {
			$(this).css({backgroundPosition:'-100px 0px'});
		});
	};
	
	jQuery.fn.mouvArretTalk = function(){
		$(this).arretTalk();
		$(this).everyTime(1200,function(){
			$(this).arretTalk();
		});
	}
	jQuery.fn.marcheTalk = function() {
		$(this).oneTime(1200,function() {
			$(this).css({backgroundPosition:'0px -271px '});
		}).oneTime(300,function() {
			$(this).css({backgroundPosition:'-100px -271px '});
		}).oneTime(600,function() {
			$(this).css({backgroundPosition:'-200px -271px '});
		}).oneTime(900,function() {
			$(this).css({backgroundPosition:'-100px -271px '});
		});
	};
	jQuery.fn.mouvMarcheTalk = function(){
		$(this).marcheTalk();
		$(this).everyTime(1200,function(){
			$(this).marcheTalk();
		});
	}
	
	var arret = 0;

	// $("#client1").click(function() {
		// if($("#onTalk").val()==0 && $("#onMyTalk").val()==0){
			// $("#texto").removeClass().addClass('client1TextCouloir');
			// if (arret == 0 || arrestation==1) {
				// $("#texto").show();
				// $("#onTalk").val(1);
				// $("#client1").stopTime().mouvMarcheGch();

				// var request = $.ajax({
				// url: url_site+"Core/index/ajaxquote", 
				// type: "POST",
				// data: { idDiv: 'client1', idPerso: '14', talk: 'mouvArretGch', stopTalk: 'mouvMarcheGch' },			
				
				// }); 
				// request.done(function(msg) { 
				// $("#texto").html(msg); 
				// });
				 
			// }else{
				// arret = 0;
				// $("#client1").stopTime().mouvArretGch();
				// $("#texto").invisible();
			// }
		// }
	// });
	
	$("#garde_couloir_1").click(function() {
		if($("#onTalk").val()==0 && $("#onMyTalk").val()==0){
			$("#texto").removeClass().addClass('garde_couloir_1TextCouloir');
			if (arret == 0 || arrestation==1) {
				$("#texto").show();
				$("#onTalk").val(1);
				$("#garde_couloir_1").stopTime().mouvMarcheTalk();

				var request = $.ajax({
				url: url_site+"Core/index/ajaxquote", 
				type: "POST",
				data: { idDiv: 'garde_couloir_1', idPerso: '12', talk: 'mouvArretTalk', stopTalk: 'mouvMarcheTalk' },			
				
				}); 
				request.done(function(msg) { 
				$("#texto").html(msg); 
				});
				 
			}else{
				arret = 0;
				$("#garde_couloir_1").stopTime().mouvArretTalk();
				$("#texto").invisible();
			}
		}
	});

$("#retour_couloir").click(function() {
	if($('#onTalk').val()==0){
		$('#onTalk').val(1);	
		var request = $.ajax({
		url: url_site+'Core/index/trone',
		type: "POST"							
		}); 
		request.done(function(msg) {
						$("#inThePlace").fadeOut(1000);
						setTimeout(function(){
						  $("#inThePlace").hide();
						  $("#inThePlace").html(msg); 
						$("#inThePlace").fadeIn(1000);
						}, 1000);
						
					});
	}
});

$(".vers_hangar").click(function() {
	if($('#onTalk').val()==0){
		$('#onTalk').val(1);
		if(<?php echo $imp;?>>=5)
			var dstination='trone';else dstination='hangar';
		var request = $.ajax({
		url: url_site+'Core/index/'+dstination,
		type: "POST",							
		}); 
		request.done(function(msg) {
						$("#inThePlace").fadeOut(1000);
						setTimeout(function(){
						  $("#inThePlace").hide();
						  $("#inThePlace").html(msg); 
						$("#inThePlace").fadeIn(1000);
						}, 1000);
						
					});
	}
});

$(".vers_couloir4").click(function() {
	if($('#onTalk').val()==0){
		$('#onTalk').val(1);
		if(<?php echo $imp;?>>=5)
			var dstination='trone';else dstination='couloir4';
		var request = $.ajax({
		url: url_site+'Core/index/'+dstination,
		type: "POST",							
		}); 
		request.done(function(msg) {
						$("#inThePlace").fadeOut(1000);
						setTimeout(function(){
						  $("#inThePlace").hide();
						  $("#inThePlace").html(msg); 
						$("#inThePlace").fadeIn(1000);
						}, 1000);
						
					});
	}
});

});
 
if($("#client1").length)
	$("#client1").mouvArretGch();
if($("#garde_couloir_1").length)
	$("#garde_couloir_1").mouvArretTalk();

$("#mesTexto").html('<img src="images/plan/couloir_plan.png" />'); 
$("#plan").val('couloir_plan');

</script>
</head>

<?php
if($this->myUser->getHeure()>=67)$stylePiece='nuit';else $stylePiece='';
$stylePiece='';
?>
<div id="<?php echo $this->salle;?>" class='<?php echo $stylePiece;?>'>
	<div class='vers_hangar'>&nbsp;</div>
	<div id="perso"></div><p>&nbsp;</p>
	<div id='retour_couloir' style='z-index:1000'></div>
	<div class='vers_couloir4' style='z-index:1000'></div>
	<?php
	
	foreach($this->porteDansSalle as $porte){
		echo '<div id="porte_'.$porte['por_id'].'" class="porte_'.$porte['por_id_type'].'_'.$porte['poru_etat'].'"></div>';
	}	?>
	<div id="texto"></div>
	<?php foreach($this->persoDansSalle as $clef => $perso){
		echo '<div class="'.$clef.'_couloir" id="'.$clef.'"></div>';
	}
	?>
</div>


