
<?php $imp=$this->myUser->getImpot();?>
<script type="text/javascript">

$(document).ready(function() {
	$("#onTalk").val(0);
	$("#onMyTalk").val(0);
	jQuery.fn.arretParleGue = function() {
		$(this).oneTime(300,function() {
			$(this).css({backgroundPosition:'0px 0px'});
		}).oneTime(600,function() {
			$(this).css({backgroundPosition:'-100px 0px'});
		}).oneTime(900,function() {
			$(this).css({backgroundPosition:'-200px 0px'});
		}).oneTime(1200,function() {
			$(this).css({backgroundPosition:'-100px 0px'});
		});
	};
	jQuery.fn.mouvArretTalk = function(){
		$(this).arretParleGue();
		$(this).everyTime(1200,function(){
			$(this).arretParleGue();
		});
	}

	jQuery.fn.parleGue = function() {
		$(this).oneTime(300,function() {
			$(this).css({backgroundPosition:'0px -270px'});
		}).oneTime(600,function() {
			$(this).css({backgroundPosition:'-100px -270px'});
		}).oneTime(900,function() {
			$(this).css({backgroundPosition:'-200px -270px'});
		}).oneTime(1200,function() {
			$(this).css({backgroundPosition:'-100px -270px'});
		});
	};
	jQuery.fn.mouvMarcheTalk = function(){
		$(this).parleGue();
		$(this).everyTime(1200,function(){
			$(this).parleGue();
		});
	}
	
	///
	var arret = 0;

	$("#soeur_1").click(function() {
		if($("#onTalk").val()==0 && $("#onMyTalk").val()==0){
			$("#texto").removeClass().addClass('soeur_1Text');
			if (arret == 0 || arrestation==1) {
				$("#texto").show();
				$("#onTalk").val(1);
				$("#soeur_1").stopTime().mouvMarcheTalk();

				var request = $.ajax({
				url: url_site+"Core/index/ajaxquote", 
				type: "POST",
				data: { idDiv: 'soeur_1', idPerso: '15', talk: 'mouvArretTalk', stopTalk: 'mouvMarcheTalk' },			
				
				}); 
				request.done(function(msg) {
				$("#texto").html(msg); 
				});
				 
			}else{
				arret = 0;
				$("#soeur_1").stopTime().mouvArretTalk();
				$("#texto").invisible();
			}
		}
	});

$("#retour_representants").click(function() {
	if($('#onTalk').val()==0){
		$('#onTalk').val(1);	
		if(<?php echo $imp;?>>=5)
			var dstination='trone';else dstination='entree';
		var request = $.ajax({
		url: url_site+'Core/index/'+dstination,
		type: "POST"							
		}); 
		request.done(function(msg) {
						$("#inThePlace").fadeOut(1000);
						setTimeout(function(){
						  $("#inThePlace").hide();
						  $("#inThePlace").html(msg); 
						$("#inThePlace").fadeIn(1000);
						}, 1000);
						
					});
	}
});

$("#porte_5").click(function() {
		if($("#onTalk").val()==0 && $("#onMyTalk").val()==0){
			if($(this).attr('class')=='porte_1_1'){
				if(<?php echo $imp;?>>=5)
					var dstination='trone';else dstination='chambre1';
				var request = $.ajax({ 
					url: url_site+'Core/index/'+dstination,
					type: "POST"							
		}); 
		request.done(function(msg) {
						$("#inThePlace").fadeOut(1000);
						setTimeout(function(){
						  $("#inThePlace").hide();
						  $("#inThePlace").html(msg); 
						$("#inThePlace").fadeIn(1000);
						}, 1000);
						
					});
			}
		}
});
$("#porte_6").click(function() {
		if($("#onTalk").val()==0 && $("#onMyTalk").val()==0){
			if($(this).attr('class')=='porte_1_1'){
				if(<?php echo $imp;?>>=5)
					var dstination='trone';else dstination='chambre2';
				var request = $.ajax({ 
					url: url_site+'Core/index/'+dstination,
					type: "POST"							
		}); 
		request.done(function(msg) {
						$("#inThePlace").fadeOut(1000);
						setTimeout(function(){
						  $("#inThePlace").hide();
						  $("#inThePlace").html(msg); 
						$("#inThePlace").fadeIn(1000);
						}, 1000);
						
					});
			}
		}
});
$("#porte_7").click(function() {
		if($("#onTalk").val()==0 && $("#onMyTalk").val()==0){
			if($(this).attr('class')=='porte_1_1'){
				if(<?php echo $imp;?>>=5)
					var dstination='trone';else dstination='chambre3';
				var request = $.ajax({ 
					url: url_site+'Core/index/'+dstination,
					type: "POST"							
		}); 
		request.done(function(msg) {
						$("#inThePlace").fadeOut(1000);
						setTimeout(function(){
						  $("#inThePlace").hide();
						  $("#inThePlace").html(msg); 
						$("#inThePlace").fadeIn(1000);
						}, 1000);
						
					});
			}
		}
});
$("#porte_8").click(function() {
		if($("#onTalk").val()==0 && $("#onMyTalk").val()==0){
			if($(this).attr('class')=='porte_1_1'){
				if(<?php echo $imp;?>>=5)
					var dstination='trone';else dstination='chambre4';
				var request = $.ajax({ 
					url: url_site+'Core/index/'+dstination,
					type: "POST"							
		}); 
		request.done(function(msg) {
						$("#inThePlace").fadeOut(1000);
						setTimeout(function(){
						  $("#inThePlace").hide();
						  $("#inThePlace").html(msg); 
						$("#inThePlace").fadeIn(1000);
						}, 1000);
						
					});
			}
		}
});


});
 
if($("#soeur_1").length)
	$("#soeur_1").mouvArretTalk();

$("#mesTexto").html('<img src="images/plan/intendant_plan.png" />'); 
$("#plan").val('intendant_plan');

</script>
</head>

<?php
if($this->myUser->getHeure()>=67)$stylePiece='nuit';else $stylePiece='';
$stylePiece='';
?>
<div id="<?php echo $this->salle;?>" class='<?php echo $stylePiece;?>'>
	<div id="perso"></div><p>&nbsp;</p>
	<div id='retour_representants' style='z-index:1000'></div>
	<?php
	
	foreach($this->porteDansSalle as $porte){
		echo '<div id="porte_'.$porte['por_id'].'" class="porte_'.$porte['por_id_type'].'_'.$porte['poru_etat'].'"></div>';
	}	?>
	<div id="texto"></div>
	<?php foreach($this->persoDansSalle as $clef => $perso){
		echo '<div class="'.$clef.'_representants" id="'.$clef.'"></div>';
	}
	?>
</div>


