<div id="inscription">
<h1>Dune jeu point and click : Récupération de votre mot de passe</h1><p>&nbsp;</p>
<h2>Si vous avez oublié votre mot de passe dans le désert d'Arrakis, nous vous offrons la possibilité d'en créer un nouveau.</h2><p>&nbsp;</p>
<h3>Pour cela, indiquez l'adresse e-mail utilisée lors de la création de votre compte.</h3><p>&nbsp;</p>
<p >Un e-mail contenant la procédure à suivre vous sera alors adressé.</p>
<?php //echo $this->form;
$this->displayMessages();
 ?>
<?php echo $this->form ?>
<a class='retourbutton butt butt2 lost' href='<?php echo URL_MAIN_ABS . $this->rewrite('Core/index/index'); ?>'><img class="first" src="/images/index/Accueil-bor_33.png" alt="dune jeu" title="dune jeu"/> RETOUR <img src="/images/index/Accueil-bor_36.png" alt="dune jeu" title="dune jeu"/></a>
<div class="librarianLost"></div>
</div>
<script>
jQuery.fn.arretTalk = function() {
		$(this).oneTime(1200,function() {
			$(this).css({backgroundPosition:'-140px 0'});
		}).oneTime(300,function() {
			$(this).css({backgroundPosition:'0 0'});
		}).oneTime(600,function() {
			$(this).css({backgroundPosition:'-140px 0'});
		}).oneTime(900,function() {
			$(this).css({backgroundPosition:'-280px 0'});
		});
	};
	
	jQuery.fn.mouvArretTalk = function(){
		$(this).arretTalk();
		$(this).everyTime(1200,function(){
			$(this).arretTalk();
		});
	}
	
$(".librarianLost").mouvArretTalk();
</script>