


<div id="inscription">
<h1>Dune jeu point and click : Récupération de votre mot de passe</h1><p>&nbsp;</p>
<h2>Création d'un nouveau mot de passe</h2><p>&nbsp;</p>
<p>&nbsp;</p>

<div class="fpasswordNew">
<?php echo $this->form; ?>
</div>
<a class='retourbutton butt butt2 lost' href='<?php echo URL_MAIN_ABS . $this->rewrite('Core/index/index'); ?>'><img class="first" src="/images/index/Accueil-bor_33.png" alt="dune jeu" title="dune jeu"/> RETOUR <img src="/images/index/Accueil-bor_36.png" alt="dune jeu" title="dune jeu"/></a>

</div>