<div id="commentjouer">
<h1>Dune jeu point and click : Situation politique</h1>
<p>L'imperiuum vit depuis plus de 3500 ans sous le joug du Tyran LETO II, puissant monarque mi-homme, mi-Ver de sable capable de clairvoyance et devinant l'avenir </p>
<p>Tout l'empire connu ne dépend que d'une seule ressource rare et précieuse : <b>l'EPICE</b>, que seul l'Empereur-dieu est capable de générer sur <strong>DUNE</strong> -communément appelé <strong>ARRAKIS</strong></p>
<p>Celui-ci, pour stabiliser et soumettre tout l'imperiuum, distribue parcimonieusement cette manne rarissime aux 4 grandes maisons restantes
<ul>
<li><a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/guilde'); ?>'>La GUILDE SPATIALE</a></li>
<li><a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/gesserit'); ?>'>Le BENE GESSERIT</a></li>
<li><a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/ix'); ?>'>IX</a></li>
<li><a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/tleilax'); ?>'>Le BENE TLEILAX</a></li>
</ul>
</p>
<p>Cette distribution d'épice est plus connue sous le nom de "Cérémonie du Partage" qui a lieu tous les 5 jours.<br/> OU QUE VOUS SOYEZ, au bout de 5 jours, vous allez être redirigé vers la salle du trône pour initier la cérémonie du 
partage</p>
<br/>
 <p><a class="commentJouer" <?php echo $cl;?> href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/apercu'); ?>'>Tutoriel en images</a></p><br/>
 <p><a class="commentJouer" <?php echo $cl;?> href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/personnages'); ?>'>Les différents personnages du palais</a></p><br/><br/>
<h3>1 - Cérémonie du partage</h3>
<p>
En tant que plus proche serviteur de l'Empereur-dieu LETO II, vous êtes responsable de la distribution d'épice accordée aux différentes maisons.
Vous pouvez (devez) paramètrer la quantité d'épice que vous allouez aux différentes maisons.</p>
<p> Plus vous allouez d'épice, plus vous obtenez de la <b>RENOMMEE</b>. Si une des maisons ne reçoit pas d'épice par manque de ressource lors d'une cérémonie, votre niveau de corruption augmente.
La corruption diminue le gain de Renommée par Cérémonie du Partage. 
</p>
<br/>
<h3>2 - Comment gagner de l'épice ?</h3>
<p>Pour gagner de l'épice, deux solutions : <br/><br/>la première, la plus simple, <b><a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/conquete'); ?>'>CONQUERIR DES PLANETES</a></b><br/> 
En conquérant des planètes, pacifiquement ou en guerroyant, vous obtiendrez un important gain d'épice à la capture
 de la planète et un revenu plus modeste tous les jours
<br/><br/>
La deuxième en réalisant des <b>QUETES</b> que vous donnent (principalement) les représentants des 4 maisons majeures du Landstraad. Plus vous réalisez des Quêtes, plus vous aurez d'épice.
 </p>
<p class='warning'>Vous DEVEZ le plus rapidement possible commencer à conquérir des planètes</p>
</br>
<h3>3 - Que me rapporte les Quêtes ? </h3>
<p>Les Quêtes que vous accomplirez vous rapporteront différentes sortes de récompense : des Objets, de l'EPICE, des Serviteurs, de l'Influence et des Escortes</p>
<p><b>Les OBJETS</b> servent à résoudre des quêtes, ou a vous apporter des bonus au cours de votre aventure. Pour en utiliser un, cliquer dessus</p>
<p><b>Les SERVITEURS</b>, une fois assignés à une maison, servent à augmenter la jauge d'humeur de cette maison. Plus une maison est heureuse, plus les représentants de ces maisons vous parleront</p>
<p><b>Les POINTS D'INFLUENCE</b>, une fois assignés à une maison, permettent de diminuer la quantité d'épice donnée à chaque cérémonie du partage pour la maison concernée</p>
<p><b>Les ESCORTES</b>, une fois assignés à une maison, protègent la maison concernée des <b>ATTENTATS</b></p>

<p class='warning'>Vous devez assigner les Serviteurs, l'Influence et les Escortes aux différentes maisons</p>
<p>Il est en effet rare de recevoir des Serviteurs, de l'Influence et des Escorte déjà assignés à une maison particulière. <br/>
Vous devez donc les assigner vous même dans votre tableau de bord, au même endroit ou vous gérez la quantité d'épice distribuée par maison</p>
<br/>
<h3>4 - Les Attentats</h3>
<p>CONTEXTE TENDU</p>
<p>Les différentes maisons présentes dans le palais n'entretiennent pas de bon rapport : elles veulent à tout prix rabaisser les autres représentants pour seules briller aux yeux de l'Empereur</p>
<p>Aléatoirement, un ou deux Serviteurs <b>DEJA ASSIGNES</b> meurent sous les coups d'un attentat perpétré par une des maisons rivales</p>
<p>LES ESCORTES meurent à la place des Serviteurs. Les Serviteurs sont extrèmement important pour s'assurer les bonnes relations d'une maison. ASSIGNEZ des Escortes aux maisons possédant des Serviteurs</p>
<br/>
<h3>Vous voila fin prêt, vous, MONEO, à vous mettre au service de votre Empereur-dieu LETO II !</h3></br></br></br>

</div>

<a class="retourAccueil2" href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/remerciements'); ?>'>Remerciements</a>
<a class='retourAccueil2 second' href='<?php echo URL_MAIN_ABS . $this->rewrite('Core/index/index'); ?>'><img class="first" src="/images/index/Accueil-bor_33.png" alt="dune jeu" title="dune jeu"/> JOUER <img src="/images/index/Accueil-bor_36.png" alt="dune jeu" title="dune jeu"/></a>
<script>$(window).load(function() {
$('#connect a').css('visibility', 'hidden');
$('#ressources, #mesTexto, #infojoueur').hide();
})</script>