<div id="commentjouer">
<h1>L'attaque dans Dune jeu point and click</h1>

<h2>Gagner de l'épice sur dune</h2>
<p>Dans <strong>dune jeu point and click</strong> il vous faudra toujours plus d'épice pour répondre aux besoins de la
 <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/apercu'); ?>'>cérémonie de partage</a> et pour acheter des objets utiles aux quêtes au surplus du palais</p>
 <p>Le meilleur moyen de récolter de l'épice est de conquérir les planètes de l'imperiuum grâce aux vaisseaux ou grâce aux ambassades</p>
<h3>PRIORITE ABSOLUE</h3>
<p>Vous devez dès que possible vous rendre dans la chambre du <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/guilde'); ?>'>représentant de la guilde spatiale</a>
 pour qu'il vous donne des bonus à chaque conquête de planète, par palier de 5.</p>
<div id="picture">
		<img src="/images/perso/representant-guilde_seul.png" alt="représentant guilde du jeu point and click" title="représentant guilde du jeu point and click"/>
	</div>
	<p>La première chose à faire dès que vous le pouvez est donc de monter dans la partie "haute" du palais qui est réservée à l'attaque des planètes de l'imperiuum.</p>
	<p>Une fois arrivé dans le hangar, vous pouvez:
		<ul>
			<li>Acheter des vaisseaux (plus vous en avez, et plus vous pouvez envahir de planètes) en prenant sur la gauche</li>
			<li>Conquérir l'imperiuum - le plus important en prenant au milieu</li>
			<li>Voir les résultats d'ambassade, en prenant à droite</li>
		</ul>
	</p>
<p>En effet, conquérir les planètes est le moyen le plus simple pour ramasser de l'épice : soit par la force en envoyant des vaisseaux, 
soit par diplomatie en envoyant une ambassade (selon le niveau de civisme de la planète) </p>
<div class="clear"></div>

<h3>Une quête cachée liée à la carte de jeu point and click</h3>
<p>La carte de l'imperiuum cache un secret bien gardé qui permet la réussite de plusieurs quêtes secondaires importantes. </p>
 <p>explorez bien toutes les salles du palais de <strong>dune jeu point and click</strong> pour comprendre de quoi il s'agit. Un important indice y est dissimulé</p>
<div>
	<img src="/images/carte.png" alt="carte du jeu point and click" title="carte de dune jeu point and click"/>
</div>
<br/>
<br/>
<h3>Le jeu Dune point and click n'a plus aucun secret pour vous !</h3>

</div>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/commentjouer'); ?>'>Quelques bases du jeu</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/apercu'); ?>'>Tutoriel en images</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Core/index/index'); ?>'>JOUER</a>
<script>$(window).load(function() {
$('#connect a').css('visibility', 'hidden');
})</script>