<div id="commentjouer">
<h1>L'épice dans l'univers du jeu point and click dune</h1>

<h2>Drogue salutaire</h2>
<p>L’Épice gériatrique, aussi appelée Mélange est une substance qui n'est produit que sur la planète Arrakis par les vers de sables qui la sécrétent. 
Longtemps convoitée par les différentes maisons majeures de l'imperiuum, à savoir, 
<a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/guilde'); ?>'>La GUILDE SPATIALE</a>, <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/gesserit'); ?>'>Le BENE GESSERIT</a>,
<a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/ix'); ?>'>IX</a>, 
<a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/tleilax'); ?>'>Le BENE TLEILAX</a>, et meme les Harkonnens et la maison Corrino
Le contrôle de l'épice a longtemps été la cause des tensions entre les différentes factions.
<h3>Les propriétés de l'épice</h3>
<p>L'épice, bien que mortelle à forte dose dans la plupart des cas, peut si elle est consommée modérément, allonger la durée de vie. 
Bien plus, elle permet d'avoir accès à la Mémoire Seconde pour les soeurs du Bene Gesserit après consommation d'une dose massive de l'épice,
 au cours d'un rituel appelé "Agonie de l'épice".</p>
 <p>La Guilde spatiale s'en sert quant à elle pour voyager dans l'hyperspace avec ses Long-courriers.</p>
 <p>L'épice, outre ses capacités gériatriques, agit aussi physiologiquement. On peut principalement citer trois effets majeurs :
	 <ul>
		 <li>Une exposition prolongée à l’Épice rend définitivement dépendant.</li>
		 <li>Chez certaines personnes, le contact avec l’épice développe des capacités de prescience.</li>
		 <li>L’absorption régulière d’épice entraîne le bleuissement intégral des yeux.</li>
	</ul>
</p>
 <p>L'adage le plus connu de tout l'univers de l'Imperiuum est le suivant "Qui contrôle l'épice, contrôle l'univers". On comprends pourquoi.</p>
<div id="picture">
		<img src="/images/perso/representant-ix-seul.png" alt="représentant ixien du jeu point and click" title="représentant ixien du jeu point and click"/>
	</div>
	<p>Evidemment, la mise sous tutelle des maisons majeures par l'Empereur-dieu a mis fin aux guerres incessantes qui animaient les maisons pour le contrôle de l'épice.</p>
<p>La disparition progressive des vers de sables de la planète Dune - ou de son vrai nom "Arrakis", seuls producteurs d'épice de tout l'univers,  
 a considérablement changé la donne. Depuis plus de 3000 ans, Le seul producteur d'épice de tout l'imperiuum est donc l'Empereur-dieu, mi-homme, mi-vers</p>
<div class="clear"></div>
<br/><br/>

<h3>Le jeu Dune point and click n'a plus aucun secret pour vous !</h3>

</div>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/commentjouer'); ?>'>Quelques bases du jeu</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/apercu'); ?>'>Tutoriel en images</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Core/index/index'); ?>'>JOUER</a>
<script>$(window).load(function() {
$('#connect a').css('visibility', 'hidden');
})</script>