<div id="commentjouer">
<h1>Les gholas dans Dune jeu point and click</h1>

<h2>Définition de Ghola dans le jeu Dune</h2>
<p>Les gholas sont des clones à la solde du <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/tleilax'); ?>'>BENE TLEILAX</a> </p>
<p>Ils sont créés à partir des restes de la dépouille de la personne décédée. Ces clones tout droit sorti des cuves Axolotl tleilaxienne gardent en eux
 la mémoire et la personnalité de la version originale sans pour autant qu'elle ne se manifeste.</p>
<h3>un ghola dans le palais du jeu Dune</h3>
<p>La présence d'un ghola dans les affaires de l'Empereur-dieu LETO II indique le haut niveau de trahison qui gravite autour de la distribution d'épice dans ce <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/apercu'); ?>'><strong>dune jeu</strong></a><strong> point and click</strong></p>
<div id="picture">
		<img src="/images/objet/laser.gif" alt="possible ghola du jeu point and click" title="possible ghola du jeu point and click"/>
	</div>
	<p>En effet, les gholas sont de redoutables assassins utilisés couramment par la maison tleilaxu. Si la présence d'un ghola dans le palais ne fait aucun doute, 
	Il vous sera néanmoins difficile de le démasquer.</p> 
	<p>Seul de subtils indices vous permettront de dénoncer cet assassin aux <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/personnages'); ?>'>truitesses</a> qui s'en chargeront.</p>
	<p>Il vous faudra pour cela activer la quête grâce aux sorcières <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/gesserit'); ?>'>Bene Gesserit</a> présentes dans le palais.</p>
	<p></p>
<div class="clear"></div>
<h3>Duncan Idaho dans ce jeu point and click</h3>
<div id="picture">
	<img src="/images/perso/Counsellor-seul.png" alt="conseiller du jeu point and click" title="conseiller de dune jeu point and click"/>
</div>
<p>Duncan Idaho est en effet le ghola le plus fameux de l'empire : Voilà plus de 3000 ans que l'Empereur-dieu LETO II fait appel aux tleilaxus pour faire revivre le
 conseiller / ami original de son père. Mais à sa demande, ce ghola ne doit pas être modifié par les tleilaxu et doit rester le plus fidèlement possible au Duncan original. Sa loyauté va donc aux Atréides.</p>
 <p>Ce pouvoir exclusif de création de ghola justifie ainsi l'existence des tleilaxu qui n'inspirent pourtant que mépris et méfiance de la part de l'Empereur-dieu. Mais l'Empereur-dieu a besoin d'eux pour recréer ce ghola à travers les âges...</p>
<p>Une quête concernant le personnage Duncan Idaho est prévu à partir du conseiller ixien de l'empereur mais elle n'a pas encore été implémantée... En effet, ce personnage clé n'est que mentionné pour le moment, mais apparaitra plus tard</p>

<h3>Le jeu Dune point and click n'a plus aucun secret pour vous !</h3>

</div>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/commentjouer'); ?>'>Quelques bases du jeu</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/apercu'); ?>'>Tutoriel en images</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Core/index/index'); ?>'>JOUER</a>
<script>$(window).load(function() {
$('#connect a').css('visibility', 'hidden');
})</script>