<div id="commentjouer">
<h1>la guilde spatiale dans Dune jeu point and click</h1>

<h2>Son représentant sur Dune</h2>
<p>Les personnages de la guilde spatiale présents dans le <strong>dune jeu point and click</strong> dépendent de la portion d'épice que vous leur allouez tous les 5 jours</p>
<h3>La guilde dans le jeu Dune</h3>
<p>La Guilde Spatiale est une des organisations du cycle de fiction de Dune. Elle fut créée en l’an 0 du calendrier impérial, celui-ci étant daté depuis sa création.Ce fut l'une des rares grandes maisons
majeures à avoir survécu à l'avènement du règne de l'Empereur-dieu LETO II</p>
<div id="picture">
		<img src="/images/perso/representant-guilde_seul.png" alt="représentant de la guilde du jeu point and click" title="représentant de la guilde du jeu point and click"/>
	</div>
	<p>Les vaisseaux sont dirigés par des Navigateurs et propulsés par des générateurs Holtzmann.
	La "Paix de LETO" interdit l'utilisation des générateurs dans les différents mondes qui composent l'Imperiuum
	Mais la nécessité de transporter les <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/personnages'); ?>'>truitesses</a> à bord des Longs-Courriers
	de la Guilde oblige l'Empereur-dieu LETO II à conserver cette maison majeure. Il s'en sert également pour <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/conquete'); ?>'>Conquérir des planètes</a></p>
	<p>C'est donc un marché que propose l'Empereur-dieu LETO II à la guilde : en échange de leurs services qui permet de maintenir la "Paix de LETO"
	à travers l'univers, L'Empereur-dieu entretient la Guilde spatiale juste assez pour qu'ils subsistent sans pour autant leur donner une influence trop importante qui pourrait menacer son pouvoir.</p>
<div class="clear"></div>
<br/><br/><br/><br/><br/>

<h3>La relation de la Guilde avec l'épice dans ce jeu point and click</h3>
<div id="picture">
	<img src="/images/perso/worker_seul.png" alt="ouvrier du jeu point and click" title="ouvrier de dune jeu point and click"/>
</div>
<p>La Guilde spatiale est la seule maison disposant de "Navigateurs", sorte de pilote de vaisseaux spatiaux, qui ont la capacité de plier le temps et l'espace pour aller d'un bout de l'univers à l'autre</p>
<p>Mais pour se faire, la Guilde a besoin d'épice en importante quantité... Or seul l'Empereur-dieu en fournit, depuis la disparition progressive des Vers de sable qui pullulaient sur Arrakis </p>
<p>Ainsi, l'Empereur-dieu entretient la Guilde Spatiale dans une dépendance qu'ils ne peuvent s'affranchir en leur donnant tous les 5 jours, lors de la Cérémonie de Partage, une quantité variable d'épice</p>

<h3>Le jeu Dune point and click n'a plus aucun secret pour vous !</h3>

</div>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/commentjouer'); ?>'>Quelques bases du jeu</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/apercu'); ?>'>Tutoriel en images</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Core/index/index'); ?>'>JOUER</a>
<script>$(window).load(function() {
$('#connect a').css('visibility', 'hidden');
})</script>