<h2>POSSESSIONS</h2>

<div id="pageContent">
            <a href="<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/infouniteuser') ?>" >Unites</a>-
            <a href="<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/infobatimentuser') ?>" >Batiments</a>-
            <a href="<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/infomagieuser') ?>" >Magie</a>
				
          </div>