<div id="commentjouer">
<h1>Paul Atréides et Dune</h1>

<h2>Il y'a 3000 ans</h2>
<p><strong>dune jeu point and click</strong> se déroule bien après l'avènement de Paul Atréides</p>
<p>Prince héritier de la maison Atréides, Paul est âgé de quinze ans quand son père, le duc Leto - à ne pas confondre avec LETO II, est tué par les Harkonnen, ennemis jurés de sa famille, alors qu'il se trouvait sur la planète Arrakis - aussi appelée Dune.</p>
<p>Paul s'enfuit de la forteresse et est recueilli par les Fremen, les habitants du désert. </p>
<p>Paul acquiert le pouvoir de prescience et devient le leader des Fremen, parvenant ainsi à renverser les Harkonnen. </p>
<p>Il créé, bien malgré lui, le jihad qui ensanglante l'imperiuum douze années durant, et devient ainsi le premier empereur Atréides, cette place étant traditionnellement réservée aux Corrinos.</p>
<p>Frappé de cécité à la suite d'un attentat manqué auquel participe la <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/guilde'); ?>'>GUILDE SPATIALE</a>,
le <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/tleilax'); ?>'>BENE TLEILAX</a> et même <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/ix'); ?>'>Les IXIENS</a>, il abdique et s'enfonce seul dans le désert, en accord avec la tradition des Fremen.</p>

<div id="picture">
		<img src="/images/perso/Leto_seul.png" alt="LETO II du jeu point and click" title="LETO II du jeu point and click"/>
	</div>
	<h3>Jihad Atréides et Sentier d'Or sur Dune</h3>
<p>l'Empereur-dieu LETO II, 3000 ans après ces faits, revient régulièrement sur le voile du futur que son père n'a jamais voulu soulevé. 
Paul ainsi que ses enfants, est prescient, c’est-à-dire qu’il sait lire l’avenir. Il avait donc vu le Sentier d'Or, si cher à LETO II, mais n'a jamais voulu assumer le rôle qu'on lui donnait.
C’est ce qui amènera sa perte lorsqu’il refusa d’assumer la responsabilité du Sentier d'Or. C’est son fils qui poursuivra finalement cette voie.</p>


<h3>Le jeu Dune point and click n'a plus aucun secret pour vous !</h3>

</div>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/commentjouer'); ?>'>Quelques bases du jeu</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/apercu'); ?>'>Tutoriel en images</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Core/index/index'); ?>'>JOUER</a>
<script>$(window).load(function() {
$('#connect a').css('visibility', 'hidden');
})</script>