<div id="commentjouer">
<h1>Quelques personnages présents dans Dune jeu point and click</h1>

<h2>Le palais de Dune</h2>
<p>Les personnages de <strong>dune jeu point and click</strong> qui se trouvent dans le palais sont pour la plupart aux ordres de LETO II</p>
<h3>LETO II</h3>
<p>Leto II est devenu au fil des millénaires un dieu vivant et tyrannique, qui poursuit sa mutation en ver géant au fil des siècles. 
Sa prescience et sa mémoire génétique quasi illimitées lui permettent de maîtriser totalement les différentes maisons qui se 
partageaient auparavant l’univers, et qui tentent à présent tant bien que mal de résister à l’immense pouvoir de l’Empereur-dieu, surnommé le « Tyran ».</p>
<div id="picture">
		<img src="/images/perso/Leto_seul.png" alt="Empereur LETO II du jeu point and click" title="Empereur LETO II du jeu point and click"/>
	</div>
	<p>L'Empereur-dieu est le chef des Truitesses, son armée impériale composée uniquement de femmes habillées en uniforme bleu. 
	Ce choix surprenant est du au fait qu'en étudiant les différentes civilisations à travers les siècles grâce à la Mémoire Seconde, 
	LETO II a trouvé un élément pacificateur et stabilisateur plus présent chez les femmes que chez les hommes</p>
	<p>En imposant sa paix forcée à travers l'univers, et en rendant toutes les maisons majeures de l'Imperiuum dépendantes de son épice qu'il est le seul à produire, 
	L'Empereur-dieu est devenu l'ennemi numéro un à abattre pour les différentes maisons, désireuses de retrouver leur indépendance. Le contexte politique de ce <strong>jeu point and click</strong>
	est donc lourd et tendu</p>
<div class="clear"></div>
<br/><br/><br/><br/><br/>

<h3>Les truitesses</h3>
<div id="picture">
		<img src="/images/perso/garde_seul.png" alt="truitesse du jeu point and click" title="truitesse de dune jeu point and click"/>
	</div>
<p>Les truitesses considèrent L'emperereur LETO II comme un dieu vivant et obeissent aveuglément aux ordres de celui-ci. 
Armée d’élite exclusivement féminine, les Truitesses prennent place dans le cycle de Dune lors du règne de Leto II. C'est lui qui les a créées, formées et même conditionnées grâce à la cérémonie
du Syanoq, qui rassemble l'élite des truitesses refaisant leur voeu à l'Empereur-dieu LETO II tous les ans.</p>
<p>Les truitesses à l'intérieur du palais sont toutes présentes dans la partie "haute" de celui-ci : de la salle du trône à la carte de l'univers,
 on peut en rencontrer 4 différentes - et même 5 en comptant l'ambassade. Ce sont elles qui sont chargées de la sécurité du palais - plusieurs quêtes sont liées à elles
 et de la gestion de l'empire galactique</p>

<h3>Le jeu Dune point and click n'a plus aucun secret pour vous !</h3>

</div>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/commentjouer'); ?>'>Quelques bases du jeu</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/apercu'); ?>'>Tutoriel en images</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Core/index/index'); ?>'>JOUER</a>
<script>$(window).load(function() {
$('#connect a').css('visibility', 'hidden');
})</script>