<div id="commentjouer">
<h1>dune jeu point and click: Merci au Landsraad !</h1>

<h2>remerciements</h2>
<p>Je tiens à remercier la communauté française de DUNE pour avoir cru en ce <strong>dune jeu</strong> <strong>point and click</strong></p>
<p>Je tiens évidemment à remercier ma boîte <a href="http://pulsar-informatique.com">Pulsar Informatique</a> pour avoir rendu possible ce développement
 en m'aménageant des heures de travail pour favoriser les projets persos - voir <a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/univers'); ?>'>Présentation de l'auteur</a></p>
<p>Pour les graphismes, il faut remercier mon frère qui a fait les décors - le tout gratuitement (ça sert à ça la famille :D ) - et pour les personnages, 
il faut remercier le grand artiste Anh Hoang, amateur des <strong>jeux dune</strong>, ça a été un plaisir de travailler avec lui</p>
<p>Une petite pensée pour la communauté des joueurs de <strong>jeu point and click</strong> de jeuxvideo.com qui m'ont bien encouragé et qui ont même réalisé les premiers personnages - merci Eclep !</p>
<p>Il faut aussi noter le travail de fond de tous les forums de création de jeux web qui 
sont très actifs sur le net et qui n'hésitent pas à donner des conseils et à s'impliquer dans la réalisation des jeux jouables directement par navigateur notamment en testant gratuitement les 
différentes version bêta qui ont pu être réalisé pour ensuite donner des comptes rendus précis de ce qui manque ou de ce qui reste à faire</p>
<p>Et enfin pour finir, merci à <strong>Frank Herbert</strong> et à son imagination fertile pour avoir créé cet univers de DUNE si profond et si inconnu encore. En créant ce  
<strong>dune jeu</strong> <strong>point and click</strong> j'éspère participer à l'expansion de cet univers sf si fantastique</p>
<br/>
<h3>Le jeu Dune point and click n'a plus aucun secret pour vous !</h3>

</div>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/commentjouer'); ?>'>Quelques bases du jeu</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/apercu'); ?>'>Tutoriel en images</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/univers'); ?>'>Présentation de l'auteur</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Core/index/index'); ?>'>RETOUR</a>
<script>$(window).load(function() {
$('#connect a').css('visibility', 'hidden');
})</script>