<div id="commentjouer">
<h1>le Bene Tleilax dans Dune jeu point and click</h1>

<h2>Son représentant sur Dune</h2>
<p>Les personnages de la maison Tleilax présents dans le <strong>dune jeu point and click</strong> dépendent de la portion d'épice que vous leur allouez tous les 5 jours</p>
<h3>La maison Tleilax dans le jeu Dune</h3>
<p>Le Bene Tleilax est conspué par le reste de l’Empire et des Maisons de l'Imperiuum, en raison du secret qui l’entoure, 
entrainant de la suspicion, mais aussi par la révulsion que cause leurs agissements et leurs manipulations génétique. 
Ce sont eux aussi qui sont à l'origine des "Danseurs-Visages" qu'on peut apercevoir dans ce <strong>jeu point and click</strong> et des fameux <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/ghola'); ?>'>gholas</a></p>
<div id="picture">
		<img src="/images/perso/representant-bene-tleilax-seul.png" alt="représentant Tleilax du jeu point and click" title="représentant Tleilax du jeu point and click"/>
	</div>
	<p>Lors de l'élimination naturelle des grandes maisons au cours de son long règne, L'Empereur-dieu a décidé de conserver la maison "abjecte" du Bene Tleilax.</p>
	<p>La maison Tleilaxu ne sert pas l'expansion de la "Paix de LETO" comme le fait <a href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/guilde'); ?>'>la Guilde Spatiale</a> 
	Mais elle possède un pouvoir que personne d'autre ne maîtrise : la production, via des manipulations génétiques de Ghola - clône - qui peut parfois être très utile à l'Empereur-dieu</p>
	<p>Malgré le dégoût qu'inspire la maison Tleilaxu à l'Empereur-dieu, Il décida de conserver cette maison majeure pour servir son plan de survie face à la "grande dispersion"</p>
<div class="clear"></div>
<br/><br/><br/><br/><br/>

<h3>La traitrise comme moyen de communication</h3>
<div id="picture">
		<img src="/images/perso/tarhani-seul.png" alt="général Tleilaxu du jeu dune point and click" title="général Tleilaxu du jeu dune point and click"/>
	</div>
<p>La maison Tleilaxu est réputée pour sa veulerie et sa tendance naturelle à la trahison. L'Empereur-dieu sait pertinament que les Tleilaxu attendent la moindre occasion qui se présentera
à eux pour prendre le pouvoir. C'est pourquoi LETO II les tient bien en dépendance en leur livrant une portion d'épice variable lors de la "Cérémonie de Partage" qui a lieu tous les 5 jours.
Lui seul possède l'Epice et lui seul le distribue à qui il veut.</p>
<p>Concrètement dans le <strong>dune jeu point and click</strong> cela se traduit par le fait que la plupart des accords que vous passerez avec les 
personnages appartenant au Bene Tleilax seront à double tranchant...</p>

<h3>Le jeu Dune point and click n'a plus aucun secret pour vous !</h3>

</div>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/commentjouer'); ?>'>Quelques bases du jeu</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Customer/index/apercu'); ?>'>Tutoriel en images</a>
<a class='retourAccueil' href='<?php echo URL_MAIN_ABS . $this->rewrite('Core/index/index'); ?>'>RETOUR</a>
<script>$(window).load(function() {
$('#connect a').css('visibility', 'hidden');
})</script>