<?php echo $this->Doctype();	?>


<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link rel="shortcut icon" type="image/x-icon" href="http://www.dune-empereur-jeu.fr/images/dune.ico"/>
<?php echo $this->headTitle()   . CRLF; ?>
<?php echo $this->headMeta()    . CRLF; ?>
<?php echo $this->headScript()  . CRLF; ?>
<?php echo $this->headLink()    . CRLF; ?>


<script language='javascript'>
	var url_site='<?php echo URL_MAIN_ABS;?>';
</script>
</head>
<body>
<div id="wrapper">

	<div id="page">
		<div id="page-bgtop">
		<!--ici mettre infos du joueur-->
			<div id="page-bgbtm">
				<div id='recompense' class='strong'><table id='recompenseValue'></table></div>
				<div id='messages'></div>
				<div id="content" style="-moz-border-radius:15px;-webkit-border-radius:15px;border-radius:15px;">
					<div id='contentGame'>
						<!-- CORPS -->
						<?php echo $this->layout()->content; ?>
						
					</div>
					<div id="connect"><?php echo $this->action( 'customerwidget', 'auth', 'Customer'); ?></div>
					<?php if($this->layout()->user->getId()){ ?>
					<div id='interface'>
						<div id='buttonRessources'>&nbsp;Confiance&nbsp;&nbsp;</div>
						<div id='resultAjax'>
							<?php echo $this->action( 'infohumeur', 'index', 'Customer'); ?>
						</div>
						<div id='buttonObjet'><p>o</p><p>b</p><p>j</p><p>e</p><p>t</p><p>s</p></div>
						<div id='mesObjets'>
							<?php 
								echo $this->action( 'objectsuser', 'index', 'Customer'); 
							?>
						</div>
						<div id='ressources'>
							<?php echo $this->action( 'inforessourcesuser', 'index', 'Customer'); ?>
						</div>
						<div id="infojoueur" >
							<?php echo $this->action( 'jours', 'index', 'Customer'); ?>
						</div>
						<div id='mesTexto'>
				
						</div>
					</div> <?php } else echo '<div id="interfaceDeconnect">&nbsp;</div>';?>
					<div style="clear: both;">&nbsp;</div>
					<p class='foot'>Copyright (c) 2016 dune-empereur-jeu.com. All rights reserved. <!--Design by <a href="http://www.pulsar-informatique.com/">Pulsar Informatique</a>.--></p>
				</div>
				<!-- end #content -->
			</div>
			
		</div>
		<div id="music"><?php if($this->nomMusique_old!='') { ?>
			<audio id="mplayer" loop autoplay><source id="sourc"  src="music/<?php echo $this->nomMusique_old;?>" type="audio/mpeg">Your browser does not support the audio element.</audio>
			<?php } ?>
		</div>
		<input type='hidden' id='onTalk' value='0' /><!-- variable à ranger dans le template : qu'une conversation à la fois !-->
		<input type='hidden' id='onMyTalk' value='0' /><!-- variable à ranger dans le template : qu'une conversation à la fois !-->
		<input type='hidden' id='noMultiple' value='0' /><!-- variable à ranger dans le template : qu'une action à la fois !-->
		<input type='hidden' id='onAutoTalk' value='0' /><!-- variable à ranger dans le template : qu'une action à la fois !-->
		<input type='hidden' id='plan' value='0' /><!-- variable à ranger dans le template : qu'une action à la fois !-->
		<input type='hidden' id='ceremonieBegin' value='0' /><!-- variable à ranger dans le template : qu'une action à la fois !-->
		<!-- end #page -->
	</div>
<?php 
if ( $this->getAppLevel() == 'development' ) {
    echo $this->printAppProfiler();
    echo $this->printDbProfiler();
}
?>
<?php //echo $this->InlineScript()  . CRLF; ?>
</body>
</html>
<script language='javascript'>
$('#mesObjets').css({'display': 'none'});
$('#contientGraph').css({'display': 'none'});

$("#buttonObjet").click(function() {

   if($('.pair').length!='' || $('.impair').length!='')return false;

	if ($('#buttonRessources, #infojoueur, #information, #buttonObjet, #mesTexto, .foot').css('display') != 'none'){
		$('#sortie_objet').css({'display': 'block'});
		$('#buttonRessources, #infojoueur, #information, #buttonObjet, #mesTexto, .foot').css({'display': 'none'});
	}
	else{
		$('#sortie_objet').css({'display': 'none'});
		setTimeout(function(){
		  $('#buttonRessources, #infojoueur, #information, #buttonObjet, #mesTexto, .foot').css({'display': 'block'})
		}, 500);
		
	}
	$( "#mesObjets" ).toggle( "drop" );
});

$("#buttonRessources").click(function() {
	if ($('#buttonObjet, #infojoueur, #information, #buttonRessources, #mesTexto, .foot').css('display') != 'none'){
		$('#sortie_graph').css({'display': 'block'});
		$('#buttonObjet, #infojoueur, #information, #buttonRessources, #mesTexto, .foot').css({'display': 'none'});
	}
	else{
		$('#sortie_graph').css({'display': 'none'});
		setTimeout(function(){
		  $('#buttonObjet, #infojoueur, #information, #buttonRessources, #mesTexto, .foot').css({'display': 'block'})
		}, 500);
		
	}
	$( "#contientGraph" ).toggle( "blind" );
});

</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74999929-1', 'auto');
  ga('send', 'pageview');

</script>
