<?php 
$messages = new Zend_Session_Namespace('messages');

$membre=new Zend_Session_Namespace('user');
			$idUser=$membre->userInfo->getId();
			if($idUser!=''){
				$user=new Customer_Model_Mapper_User();
				$us=new Customer_Model_User();
				$user->find($idUser, $us);
			}
        // Pour chaque type de message, affiche si non vide
        if ( is_array($messages->success) && 0 != count($messages->success) ) {
            print '<p class="success">';
            foreach( $messages->success as $message ){
                print $message . '<br />';
				
			if($idUser!=''){	
				$rap = json_decode($us->getRapport(),true);
				$rap['recompense'][] = $message;
				$rap = json_encode($rap);
				$us->setRapport($rap);
				$user->save($us);
			}
			
            }
            print '</p>';
            $messages->success = array();
        }
        if (  is_array($messages->warning) && 0 != count($messages->warning) ) {
            print '<p class="warning">';
            foreach( $messages->warning as $message ){
                print $message . '<br />';
				
				if($idUser!=''){	
					$rap = json_decode($us->getRapport(),true);
					$rap['recompense'][] = $message;
					$rap = json_encode($rap);
					$us->setRapport($rap);
					$user->save($us);
				}
				
				
            }
            print '</p>';
            $messages->warning = array();
        }
        if ( is_array($messages->error) && 0 != count($messages->error) ) {
            print '<p class="error">';
            foreach( $messages->error as $message ){
                print $message . '<br />';
				
				if($idUser!=''){	
					$rap = json_decode($us->getRapport(),true);
					$rap['rapport'][] = $message;
					$rap = json_encode($rap);
					$us->setRapport($rap);
					$user->save($us);
				}
				
            }
            print '</p>';
            $messages->error = array();
        }